"""
Immutable definitions for the Vision Encoder domain.
Represents the discrete states of image artifacts and their semantic mappings.
"""

from dataclasses import dataclass
from pathlib import Path

@dataclass(frozen=True)
class PhysicalImageReference:
    """
    An immutable pointer to the continuous image tensor generated by the upstream structurizer.
    Stores the filesystem reference to prevent premature RAM/VRAM allocation.
    """
    file_path: Path
    file_size_bytes: int

    def __post_init__(self) -> None:
        if not self.file_path.exists():
            raise FileNotFoundError(f"Image tensor artifact not found at {self.file_path}")

@dataclass(frozen=True)
class SemanticDescription:
    """
    The discrete language representation of the continuous image tensor.
    Maps to the \Sigma^* string space to replace the [ALT Text] structural node.
    """
    content: str
    metadata: dict[str, str]
